Showing Usage Of Session Override (Codeception 2.5)
Codeception/phalcon-demo pull request #12
Opened 2018-10-20 03:06 UTC by Fenikkusu

Hello!

* Type: new feature | documentation

This pull request affects the following components: **(please check boxes)**

* [ ] Project Core
* [ ] Code Style
* [ ] Documentation
* [ ] Testing

**In raising this pull request, I confirm the following (please check boxes):**

- [ ] I have read and understood the [Contributing Guidelines](https://github.com/Codeception/phalcon-demo/blob/master/CONTRIBUTING.md)?
- [ ] I have checked that another pull request for this purpose does not exist.
- [ ] I wrote some tests for this PR.

Small description of change:

Adding testing to demonstrate new feature for adding custom session object when running Codeception tests.

Thanks

2018-10-23 05:19 UTC, sergeyklay requested changes

2018-10-23 05:19 UTC, sergeyklay commented on tests/functional/SessionCest.php
> +        $I->assertTrue($I->grabServiceFromContainer('session')->getTrue());
```
PHP Fatal error: 
Call to undefined method Codeception\Lib\Connector\Phalcon\MemorySession::getTrue()
in /home/travis/build/Codeception/phalcon-demo/tests/functional/SessionCest.php on line 7
```

2018-10-23 08:29 UTC, DavertMik commented on tests/functional/SessionCest.php
> +        $I->assertTrue($I->grabServiceFromContainer('session')->getTrue());
Yes, this feature is about to come into Codeception 2.5.1 so test is not passing yet

2018-10-23 08:30 UTC, DavertMik commented on tests/functional/SessionCest.php
> +        $I->assertTrue($I->grabServiceFromContainer('session')->getTrue());
See https://github.com/Codeception/Codeception/pull/5232

2018-10-23 10:03 UTC, sergeyklay commented on tests/functional/SessionCest.php
> +        $I->assertTrue($I->grabServiceFromContainer('session')->getTrue());
@DavertMik As you can see tests was failed ¯\_(ツ)_/¯

2020-01-07 12:21 UTC, ruudboon commented
Now that V2 is released Codeception runs on v4 I'm closing this.

2020-01-07 12:21 UTC, closed without merging